#!/bin/bash

PANEL_FIFO=/tmp/panelfifo
PANEL_FIFO_CENTER=/tmp/panelfifo_center
PANEL_FIFO_LEFT=/tmp/panelfifo_left
PANEL_FIFO_RIGHT=/tmp/panelfifo_right

FG='#FFFFFFFF'
BG='#11000000'
FONT="-*-liberation mono-medium-r-*-*-12-*-*-*-*-*-*-*"

if [ $HOSTNAME = "johan-desktop" ]; then
	FIFOS="$PANEL_FIFO $PANEL_FIFO_LEFT $PANEL_FIFO_CENTER $PANEL_FIFO_RIGHT"
else
	FIFOS="$PANEL_FIFO"
fi

for FIFO in $FIFOS
  do
	[ -e "$FIFO" ] && rm "$FIFO"
	mkfifo $FIFO
done

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &


if [ $HOSTNAME = "johan-desktop" ]; then
	cat "$PANEL_FIFO"   | tee -a $PANEL_FIFO_CENTER $PANEL_FIFO_LEFT $PANEL_FIFO_RIGHT &
	cat "$PANEL_FIFO_CENTER" | ~/.bspwm/bartext 2 | lemonbar -p -B $BG -F $FG -f "$FONT" &
	cat "$PANEL_FIFO_LEFT" | ~/.bspwm/bartext 1 | lemonbar -p -B $BG -F $FG -f "$FONT" &
	cat "$PANEL_FIFO_RIGHT" | ~/.bspwm/bartext 3 | lemonbar -p -B $BG -F $FG -f "$FONT" &
else
	cat "$PANEL_FIFO" | ~/.bspwm/bartext 0 | lemonbar -p -B $BG -F $FG -f "$FONT" &
fi
$(
while true
  do
	echo T > $PANEL_FIFO
	sleep 60
done
) &
