#!/bin/sh

if [ -z $1 ]; then
	screenC=1
else
	screenC=$1
fi

NORMIFS=$IFS
FIELDIFS=':'

declare -a WORKSPACESCREEN

while read -r line ; do
	OUTPUT=""
	for screenN in $(seq 1 $screenC);
	do
		case $line in
			V*) # Empty for updating volume level
				;;
			T*) # Empty for updating time
				;;
			W*)
				# bspwm internal state
				IFS=$FIELDIFS
				set -- ${line#?}
				WORKSPACE=""
				while [ $# -gt 0 ] ; do
					item=$1
					case $item in
						[OoFfUu]*)
							# desktops
							name=${item#?}
							case $item in
								O*) # focused occupied desktop
									FG='#FFFFFF'
									BG='#AAAAAA'
									PRE=" "
									POST=" "
									;;
								F*) # focused free desktop
									FG='#FFFFFF'
									BG='#AAAAAA'
									PRE=" "
									POST=" "
									;;
								U*) # focused urgent desktop
									FG='#FF0000'
									BG='#AAAAAA'
									PRE=" "
									POST=" "
									;;
								o*) # occupied desktop
									FG='#FFFFFF'
									BG='-'
									PRE=""
									POST=""
									;;
								f*) # free desktop
									FG="#AAAAAA"
									BG='-'
									PRE=""
									POST=""
									;;
								u*) # urgent desktop
									FG='#FF0000'
									BG='-'
									PRE=""
									POST=""
									;;
							esac
							PRE="%{F"$FG"}%{B"$BG"}"$PRE
							POST=$POST"%{B-}%{F-}"
							WSD="$PRE${name:1:1}$POST "
							if [ "$screenC" > 0 ]; then
								if [ "$screenN" = "${name:0:1}" ]; then
									WORKSPACE=$WORKSPACE$WSD
								fi
							else
								WORKSPACE=$WORKSPACE$WSD
							fi
							WORKSPACESCREEN[$screenN]=$WORKSPACE
							;;
						L*)
							# LAYOUT
							LAYOUT=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
							
							if [ "$LAYOUT" = 'T' ]; then
								li="Tile"
							elif [ "$LAYOUT" = 'M' ]; then
								li="Full"
							fi
							LAYOUT=$li
							;;
						esac
					shift
				done
				IFS=$NORMIFS
				;;
		esac
		
		#	
		#	Applets
		#
	
		# Left
		WORKSPACE=${WORKSPACESCREEN[$screenN]}
		
		# Center
		TIME=$(date +'%H:%M')
		
		# Right
		#Volume
		VOLUME="Vol: "$(~/Scripts/volume.sh get)
		# System load
		SYSLOAD=$( uptime | awk '{ printf "Load %.2f",$8 }' )
		# Battery
		if [ $(uname -n) = "johan-laptop" ]; then
			BATTERY=$(acpi | awk '{print $4}')
			BATTERY=${BATTERY:0:3}
			BATTERY='Bat: '$BATTERY
		fi
		# Memory free
		MEMFREE=$( free | grep Mem | awk '{print $3/$2 * 100.0}')
		MEMFREE=$( cut -d '.' -f 1 <<< $MEMFREE )
		MEMFREE="Ram: "${MEMFREE:0:2}"%"
	
		# Sysload
	
	
			
		#
		# Right
		#

		# For single monitor setups and laptops
		if [ $screenC = 1 ]; then
			RIGHT=$VOLUME" | "$BATTERY" "
		# Workspace specific for multi monitor setups
		elif [ $screenN = 1 ]; then
			RIGHT=" "$MEMFREE" | "$SYSLOAD" "
		elif [ $screenN = 2 ]; then
			RIGHT=""
		elif [ $screenN = 3 ]; then
			RIGHT="$VOLUME"
		fi
		
		#
		#	Alignment and concatination
		#
		
		# Left
		LEFT="${WORKSPACE}"
		LEFT="%{l} $LEFT"
	
		# Center
		CENTER="$TIME"
		CENTER="%{c}$CENTER"

		RIGHT="%{r}"$RIGHT" "

		SCREEN="%{S"$(($screenN-1))"}"
		SCREENOUTPUT="$SCREEN$LEFT$CENTER$RIGHT"
		OUTPUT=$OUTPUT$SCREENOUTPUT
	done
	echo "$OUTPUT"
done
