#!/bin/sh

if [ -z $1 ]; then
	workspaceN=0
else
	workspaceN=$1
	SCREEN="%{S"$(($1-1))"}"
fi

PANEL_FIFO_LEFT=/tmp/minipanelfifo_left
PANEL_FIFO_RIGHT=/tmp/minipanelfifo_right

NORMIFS=$IFS
FIELDIFS=':'

while read -r line ; do
	case $line in
		V*) # Empty for updating volume level
			;;
		T*) # Empty for updating time
			;;
		W*)
			# bspwm internal state
			IFS=$FIELDIFS
			set -- ${line#?}
			WORKSPACE=""
			while [ $# -gt 0 ] ; do
				item=$1
				case $item in
					[OoFfUu]*)
						# desktops
						name=${item#?}
						case $item in
							O*) # focused occupied desktop
								FG='#00DDFF'
								PRE="["
								POST="]"
								;;
							F*) # focused free desktop
								FG='#00DDFF'
								PRE="["
								POST="]"
								;;
							U*) # focused urgent desktop
								FG='#FF0000'
								PRE="["
								POST="!]"
								;;
							o*) # occupied desktop
								FG='#2288FF'
								PRE=""
								POST=""
								;;
							f*) # free desktop
								FG="#FFFFFF"
								PRE=""
								POST=""
								;;
							u*) # urgent desktop
								FG='#FF0000'
								PRE=""
								POST="!"
								;;
						esac
						PRE="%{F"$FG"}"$PRE
						POST=$POST"%{F-}"
						WSD="$PRE${name:1:1}$POST "
						if [ "$workspaceN" != 0 ]; then
							if [ "$workspaceN" = "${name:0:1}" ]; then
								WORKSPACE=$WORKSPACE$WSD
							fi
						else
							WORKSPACE=$WORKSPACE$WSD
						fi
						;;
					L*)
						# LAYOUT
						LAYOUT=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
						
						if [ "$LAYOUT" = 'T' ]; then
							li="Tile"
						elif [ "$LAYOUT" = 'M' ]; then
							li="Full"
						fi
						LAYOUT=$li
						;;
				esac
				shift
			done
			IFS=$NORMIFS
			;;
	esac
	
	#	
	#	Applets
	#

	# Left
	
	# Workspace

	# Layout
	LAYOUTCOLOR="#55FF55"
	LAYOUT="%{F"$LAYOUTCOLOR"}"$LAYOUT"%{F-}"
	
	# Center
	TIME=$(date +'%H:%M')
	
	# Right
	#Volume
	VOLUME="Vol: "$(~/Scripts/volume.sh get)
	# Icon tray space for trayer
	TRAY="|           "
	# System load
	SYSLOAD=$( uptime | awk '{ printf "Load %.2f",$8 }' )
	# Battery
	if [ "$HOSTNAME" -eq "johan-laptop" ]; then
		BATTERY=$(acpi | awk '{print $4}')
		BATTERY=${BATTERY:0:3}
		BATTERY='Bat: '$BATTERY
	fi
	# Memory free
	MEMFREE=$( free | grep Mem | awk '{print $3/$2 * 100.0}')
	MEMFREE=$( cut -d '.' -f 1 <<< $MEMFREE )
	MEMFREE="Ram: "${MEMFREE:0:2}
	# Swap usage
	SWAPFREE="Swap: "$(cat /proc/swaps | grep partition | awk '{printf "%i",(($4+1)/$3)}')

	#
	#	Alignment and concatination
	#
	
	# Left
	LEFT="${WORKSPACE}| ${LAYOUT}"
	LEFT="%{l} $LEFT"

	# Center
	CENTER="$TIME"
	CENTER="%{c}$CENTER"

	#Right
	# Workspace specific for multi monitor setups
	if [ $workspaceN = 1 ]; then
		RIGHT=$SWAPFREE" | "$MEMFREE" | "$SYSLOAD
	elif [ $workspaceN = 2 ]; then
		RIGHT="$VOLUME"
	elif [ $workspaceN = 3 ]; then
		RIGHT="$TRAY"
	else # For single monitor setups and laptops
		RIGHT=$VOLUME" | "$BATTERY" | "$TRAY" "
	fi
	# Move
	RIGHT="%{r}"$RIGHT" "

	printf "%s\n" "$SCREEN$LEFT$CENTER$RIGHT"
done
