#!/bin/sh

#
bspc config border_width	1
#bspc config window_gap		6
bspc config window_gap		0
bspc config top_padding		20

bspc config click_to_focus  true
bspc config pointer_follows_monitor  true

#
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
#bspc config focus_by_distance   true

# Setup workspaces for desktop and laptop
if [ $HOSTNAME = "johan-desktop" ]; then
	#bspc monitor DVI-I-0 -d 11 12 13 14 15
	#bspc monitor DVI-D-0 -d 21 22 23 24 25
	#bspc monitor HDMI-1  -d 31 32 33 34 35 
	bspc monitor ^1  -d 11 12 13 14 15 
	bspc monitor ^2  -d 21 22 23 24 25 
	bspc monitor ^3  -d 31 32 33 34 35 
else
	bspc monitor -d 11 12 13 14 15
fi

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}


#
#	Colors
#

# Active = Selected window at unfocused monitor
# Focused = selected window at focused monitor

bspc config focused_border_color '#999999'
bspc config active_border_color  '#444444'
bspc config normal_border_color  '#444444'
bspc config urgent_border_color  '#FF0000'

#bspc config focused_border_color '#CCCCCCAA'
#bspc config active_border_color  '#777777AA'
#bspc config normal_border_color  '#666666AA'
#bspc config urgent_border_color  '#FF0000CC'

