#!/bin/sh
MONITOR=$(bspc query -M -m)

if [ $HOSTNAME = "johan-desktop" ]; then
	if [ $MONITOR = "DVI-I-0" ]; then
		MONITOR_NUM=3
	elif [ $MONITOR = "HDMI-0" ]; then
		MONITOR_NUM=1
	else
		MONITOR_NUM=2
	fi
else
	MONITOR_NUM=1
fi

echo $MONITOR_NUM
