#!/bin/sh
#MONITOR=$(bspc query -M -m)
MONITOR=$(bspc query -M | grep -n $(bspc query -M -m) | tr ':' '\n' | head -n 1)
echo $MONITOR

#if [ $HOSTNAME = "johan-desktop" ]; then
#	if [ $MONITOR = "DVI-I-0" ]; then
#		MONITOR_NUM=1
#	elif [ $MONITOR = "HDMI-1" ]; then
#		MONITOR_NUM=3
#	else
#		MONITOR_NUM=2
#	fi
#else
#	MONITOR_NUM=1
#fi
#
#echo $MONITOR_NUM
