#!/bin/sh
MONITOR=$(bspc query -M -m)
if [ $MONITOR = "DVI-I-0" ]; then
	MONITOR_NUM=1
fi
if [ $MONITOR = "DVI-D-0" ]; then
	MONITOR_NUM=2
fi
if [ $MONITOR = "HDMI-1" ]; then
	MONITOR_NUM=3
fi


WORKSPACENAME=$MONITOR_NUM$1
echo $WORKSPACENAME

bspc window -d $WORKSPACENAME
