#!/bin/bash

PANEL_FIFO=/tmp/panelfifo
PANEL_FIFO_CENTER=/tmp/panelfifo_center
PANEL_FIFO_LEFT=/tmp/minipanelfifo_left
PANEL_FIFO_RIGHT=/tmp/minipanelfifo_right

FONT='Liberation Mono'
OPACITY=60
FG='#FFFFFF'

for FIFO in $PANEL_FIFO $PANEL_FIFO_LEFT $PANEL_FIFO_CENTER $PANEL_FIFO_RIGHT
  do
	[ -e "$FIFO" ] && rm "$FIFO"
	mkfifo $FIFO
done

H=20
L_X=100
L_W=$((1280-200))
C_X=$((1280+200))
C_W=$((1920-400))
R_X=$((1280+1920+100))
R_W=$((1280-200))

LAPTOP_X=100
LAPTOP_W=$((1379-200))

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

if [ $HOSTNAME = "johan-desktop" ]; then
	cat "$PANEL_FIFO"   | tee -a $PANEL_FIFO_CENTER $PANEL_FIFO_LEFT $PANEL_FIFO_RIGHT &
	cat "$PANEL_FIFO_CENTER" | ~/.bspwm/paneltext $C_W 2 | dzen2 \
			-ta l -o $OPACITY -fn "$FONT" -fg $FG \
			-x $C_X -y 0 -w $C_W -h $H &
	cat "$PANEL_FIFO_LEFT" | ~/.bspwm/paneltext $L_W 1 | dzen2 \
			-ta l -o $OPACITY -fn "$FONT" -fg $FG \
			-x $L_X -y 0 -w $L_W -h $H &
	cat "$PANEL_FIFO_RIGHT" | ~/.bspwm/paneltext $R_W 3 | dzen2 \
			-ta l -o $OPACITY -fn "$FONT" -fg $FG \
			-x $R_X -y 0 -w $R_W -h $H &
else
	cat "$PANEL_FIFO" | ~/.bspwm/paneltext $C_W | dzen2
fi
