#!/bin/sh

#
#	Base colors
#

color_white='#FFFFFF90'
color_black='#00000090'

color_red='#FF000090'
color_green='#00FF0090'
color_blue='#0000FF90'
color_yellow='#00FFFF90'

#
#	Appearance
#

color_bg=$COLOR_BLACK
color_fg=$COLOR_WHITE

color_fg='#FFA3A6AB'
color_bg='#FF34322E'

color_active_monitor_fg='#FF34322E'
color_active_monitor_bg='#FF58C5F1'

color_inactive_monitor_fg='#FF58C5F1'
color_inactive_monitor_bg='#FF34322E'

color_urgent_fg='#FFF9A299'
color_urgent_bg='#FF34322E'

color_title_fg='#FFA3A6AB'
