#!/bin/bash

# Setup monitors
$(
	if [ "$HOSTNAME" = "johan-desktop" ]
	  then
		xrandr --output DVI-I-0 --pos 0x0
		xrandr --output DVI-D-0 --right-of DVI-I-0 --primary --mode 1920x1080
		xrandr --output HDMI-1 --right-of DVI-D-0
	# Set wallpaper
		feh --no-xinerama --bg-fill ~/Downloads/whiterun\ triple\ monitor.png
	else
		feh --bg-fill ~/Dropbox/Photos/Wallpapers/mat\ zo\ -\ damage\ control.jpg
	fi
) &

# Set mouse cursor
xsetroot -cursor_name left_ptr &

# Panel
$HOME/.bspwm/panel &
# Tray icons
trayer \
	--edge top \
	--align right \
	--transparent true \
	--widthtype pixel \
	--heighttype pixel \
	--width 68 \
	--height 20 \
	--margin $((100+20)) \
	--tint 0x000000 &

# Autostart applications
dropboxd &




compton &
sxhkd -c ~/.bspwm/sxhkdrc &
exec bspwm -c ~/.bspwm/bspwmrc
