set number
syntax on

" Space as mapleader
"let mapleader = "\<Space>"

" Automatically adds curlybraces
filetype indent on

" Sets tab to space
set expandtab
set tabstop=4

" Encoding 
set laststatus=2
set encoding=utf-8
set t_Co=256

" Scrollwheel
set mouse=a
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>

