#!/bin/sh

xrandr --output CRT1 --primary
xrdb -merge .Xresources
xsetroot -cursor_name left_ptr
if (hostname=='johan-netbook'); then
    setxkbmap -model thinkpad -layout se
fi

sh /home/johan/.xmonad/auto-hibername.sh &
compton &
sh '/home/johan/.xmonad/setbackground.sh' &
redshift -t 6500:5200 &

/usr/bin/xmonad
